FROM ghcr.io/nginxinc/nginx-unprivileged:stable-alpine

ENV TITLE="container title"

# Install ngssc binary
ADD --chmod=0755 dist/cli/ngssc_64bit /usr/sbin/ngssc

# Add configuration template
#COPY test/default.conf.template /etc/nginx/conf.d/
COPY test/default.conf.template /etc/nginx/ngssc-templates/

# Add ngssc init script
COPY --chmod=0755 test/ngssc.sh /docker-entrypoint.d/ngssc.sh

# Copy app
COPY --chmod=0666 dist/ngssc-app/browser /usr/share/nginx/html
