version: "3.5"
services:
  build-go:
    build: ./cli
    volumes:
      - ".:/src"
      - "./dist/cli:/dist"
    environment:
      - VERSION=${npm_package_version}
    command: ["/src/scripts/build-cli.sh"]
  local-test:
    build:
      context: .
      dockerfile: test/Dockerfile.test
    environment:
      - VARIABLE=value
      - MANUAL_KEY=key
    ports:
      - 8080:8080